sudo: false
language: node_js
node_js:
  - 8

cache:
  bundle: true
  directories:
    - node_modules

install:
  - npm install

before_script:
  - npm install codecov
script:
  - npm run test:cover
after_script:
  - codecov --token=$CODECOV_TOKEN


before_deploy:
  - npm run client:build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN} # Set in travis-ci.org dashboard
  local_dir: public
  target-branch: master
  repo: $GH_REF

env:
  global:
    - GH_REF=telescopejs/telescopejs.github.io

