sudo: false
language: node_js
node_js:
  - 8

cache:
  bundle: true
  directories:
    - node_modules

install:
  - npm install

install:
  - npm install

jobs:
  include:

    - stage: Unit testing
      before_script: npm install codecov
      script: npm test:cover
      after_script: codecov --token=$CODECOV_TOKEN

    - stage: E2E testing
      script: npm run test:cy:ci $CYPRESS_RECORD_KEY

    - stage: deploy
      script: npm run client:build
      node_js: stable
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: ${GH_TOKEN} # Set in travis-ci.org dashboard
        local_dir: public
        target-branch: master
        repo: $GH_REF
        env: GH_REF=telescopejs/telescopejs.github.io
